const jsonata = require('jsonata')
const src = `{ 
    "externalUserId": id,
    "source": 'yodata-real-living',
    "meta": additionalProperty,
    "metaOrgKeys": identifier,
    "orgLabel": null,
    "status": additionalProperty.Status,
    "localLanguage": availableLanguage.name,
    "localCountry": address[country][0].country,
    "email": **.email,
    "firstName": givenName,
    "middleInitial": null,
    "lastName": familyName,
    "street1": $join(address[0].streetAddress,', '),
    "street2": null,
    "city": address[0].addressLocality,
    "state": address[0].addressRegion,
    "country": address[0].addressCountry,
    "postalCode": address[0].postalCode,
    "userImageUrl": image.url,
    "companyId": additionalProperty.AffiliateID,
    "officeId": additionalProperty.OfficeID,
    "officeName": additionalProperty.OfficeDBA,
    "officeUrl": null,
    "officeEmail": null,
    "agentProfilePage": '???',
    "phone1": contactPoint[telephone][0].telephone,
    "phone1Type": contactPoint[telephone][0].name,
    "phone2": contactPoint[telephone][1].telephone,
    "phone2Type": contactPoint[telephone][1].name,
    "phone3": contactPoint[telephone][2].telephone,
    "phone3Type": contactPoint[telephone][2].name,
    "timeZoneId": null,
    "title": jobTitle,
    "license": permit.identifier,
    "designation": '???',
    "facebookUrl": url[$contains("facebook")],
    "twitterUrl": url[$contains("twitter")],
    "linkedInUrl": url[$contains("linkedin")]
}`
const expression = jsonata(src)

module.exports = data => expression.evaluate(data)